config/routes.rb
GrabcadTestAssignment::Application.routes.draw do
  #Authentication
  root 'security/authentication#show_login_page'
  post '/login' => 'security/authentication#login'
  get '/logout' => 'security/authentication#logout'

  #Comment resource
  resources :comment, only: [:index, :create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :comment
  belongs_to :user

  def is_author?(user_id)
    self.user.id == user_id
  end
end

app/models/privilege.rb
class Privilege < ActiveRecord::Base
  ADMIN = 'admin'

  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :privileges
  has_many :comments
  has_secure_password

  before_save { username.downcase! }
  validates :username, presence: true, uniqueness: {case_sensitive: false}

  def is_admin?
    admin_privileges = self.privileges.select { |p| p.name == Privilege::ADMIN }
    !admin_privileges.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Security::AuthenticationHelper
  layout 'content_with_menu'

  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception

  before_action :setup_log_context, :require_login

private
  #Redirects user to login page if user is not logged in
  def require_login
    unless logged_in?
      redirect_to root_path
    end
  end

  #Adds tags to each log message - username and browser information
  def setup_log_context
    logger.push_tags logged_in_username
    logger.push_tags get_browser
  end

  def get_browser
    request.env['HTTP_USER_AGENT']
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  include CommentHelper

  before_action :check_destroy_permission, only: :destroy

  def index
    @comments = Comment.all
  end

  def destroy
    comment = Comment.find_by_id(params[:id])

    if comment
      comment.destroy!
      flash[:notice] = I18n.t 'comment_deleted'
    end

    redirect_to comment_index_path
  end

  def create
    user = User.find_by_id(logged_in_user_id)
    new_comment = user.comments.create(params[:new_comment].permit(:comment))

    if new_comment.valid?
      flash[:notice] = I18n.t 'comment_added'
    else
      flash[:error] = new_comment.errors.full_messages.to_sentence
    end

    redirect_to comment_index_path
  end

  private
  #Checks if user is authorized to delete the comment
  def check_destroy_permission
    comment = Comment.find_by_id(params[:id])
    unless can_delete? comment
      logger.warn 'User tried to delete someone else\'s comment'
      redirect_to comment_index_path
    end
  end
end

app/controllers/security/authentication_controller.rb
class Security::AuthenticationController < ApplicationController
  include Security::AuthenticationHelper

  layout 'application'

  skip_before_filter :require_login, only: [:show_login_page, :login]

  def show_login_page
    if logged_in?
      redirect_to comment_index_path
    end
  end

  def login
    param_username = params[:authentication][:username]
    param_password = params[:authentication][:password]

    user = User.find_by_username(param_username.downcase)
    if user && user.authenticate(param_password)
      handle_successful_login(user)
    else
      handle_failed_login(param_username)
    end
  end

  def logout
    flash[:notice] = I18n.t 'logout_notice'
    reset_session
    logger.info 'User logged out'
    redirect_to root_path
  end

  private
  def handle_successful_login(user)
    remember_logged_in_user user
    logger.info "Login successful, username: #{logged_in_username}"
    redirect_to comment_index_path
  end

  def handle_failed_login(param_username)
    flash[:error] = I18n.t 'login_error'
    logger.warn "Login failed, tried username: #{param_username}"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
  def can_delete?(comment)
    comment.is_author?(logged_in_user_id) || logged_in_user.is_admin?
  end
end

app/helpers/security/authentication_helper.rb
module Security::AuthenticationHelper
  def logged_in_user_id
    session[:logged_in_user_id]
  end

  def logged_in_username
    session[:logged_in_username]
  end

  def logged_in_user
    #noinspection RailsChecklist05
    User.find_by_id logged_in_user_id
  end

  def logged_in?
    !!logged_in_user_id
  end

  def remember_logged_in_user(user)
    session[:logged_in_user_id] = user.id
    session[:logged_in_username] = user.username
  end
end

app/views/comment/_comments_table.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th class="span2"><%= t('user') %></th>
    <th class="span9"><%= t('comment') %></th>
    <th class="span1"></th>
  </tr>
  </thead>

  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.user.username %></td>
      <td><%= comment.comment %></td>
      <td>
        <% if can_delete? comment %>
          <%= link_to t('delete'),
                      comment_path(comment),
                      method: :delete,
                      data: {confirm: t('comment_deletion_confirmation')},
                      class: 'btn btn-danger btn-small' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/comment/_form.html.erb
<div class="row">
  <div class="span12">
    <%= form_for :new_comment, url: comment_index_path, html: {class: 'form-horizontal well'} do |f| %>
      <div class="control-group">
        <%= f.label :comment, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :comment, class: 'input-xxlarge', rows: 3 %>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit t('add_comment'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comment/index.html.erb
<h3><%= t('comments_block_title') %></h3>
<%= render :partial => 'comments_table' %>
<%= render :partial => 'form' %>

app/views/layouts/_top_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <span class="brand"><%= t('app_name') %></span>
      <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right" id="main-menu-right">
          <li><%= link_to t('log_out'), logout_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="topbar-padding"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('app_name')%></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= content_for?(:content) ? yield(:content) : yield %>

</body>
</html>

app/views/layouts/content_with_menu.html.erb
<% content_for :content do %>
  <div class="container">
    <%= render :partial => 'layouts/top_menu' %>
    <%= render :partial => 'shared/messages' %>
    <%= yield %>
  </div>
<% end %>

<%= render template: 'layouts/application' %>

app/views/security/authentication/show_login_page.html.erb
<div class="container">
  <div class="topbar-padding"></div>

  <div class="row">
    <div class="span8 offset2">
      <%= form_for :authentication, url: login_path, html: {class: 'form-horizontal well'} do |f| %>
        <%= render :partial => 'shared/messages' %>

        <div class="control-group">
          <%= f.label :username, class: 'control-label' %>
          <div class="controls">
          <%= f.text_field :username, class: 'input-large' %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :password, class: 'control-label' %>
          <div class="controls">
            <%= f.password_field :password, class: 'input-large' %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit t('log_in'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>